version: "3.8"

volumes:
  mysql-data:

services:
  db:
    build: ./db
    env_file:
      - ./db/.env.prod
    ports:
      - "6033:3306"
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql

  api:
    build: ./api
    env_file: ./api/.env.prod
    ports:
      - "4321:4321"
    depends_on:
      - db
    restart: on-failure
  app:
    image: class_points_app
    build: ./app
    environment:
      API_URL: http://localhost:4321/api
   
    ports:
      - 4000:3000
